# fly.toml app configuration file generated for backend-withered-feather-1324 on 2024-10-25T19:05:27Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-withered-feather-1324'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
